### ISSUE TITLE
Images are always null 

### ISSUE THREAD

**Issue by tidusjar** [henrikfroehling/TraktApiSharp#73]
- Version: 1.0.0-alpha1-fixed-issue59
 
**Code**

```
 await Client.Shows.GetPopularShowsAsync(new TraktExtendedInfo { Full = true, Images = true}, null, 1, 10);
```
It seems that the Images seems to always be null:
![image](https://cloud.githubusercontent.com/assets/6642220/26452678/b9cd4984-4158-11e7-8e44-17e58a440aab.png)

Is there something I need to do?

**Comment by henrikfroehling** [comment]
Images (except user avatars) are no longer supported by the Trakt API. See issues #32 and #43 for more info.
The changes are planned for version 1.0.0-alpha2.
Nonetheless, the `Images` option shouldn't be there, because it was removed before and therefore shouldn't be in the latest NuGet-package (v1.0.0-alpha1-fixed-issue59). Must be some kind of merge error.

**Comment by henrikfroehling** [comment]
My mistake, the `Images`-option is still available in the latest NuGet package. Changes to `ExtendedInfo` were made after that (based on the commit/tag history) and will be in version 1.0.0 alpha 2.

**Comment by tidusjar** [comment]
Ah ok. So no more images then? That's a strange choice! Thanks for informing me so fast!

**Comment by henrikfroehling** [comment]
No, no more images, at least not from trakt.tv.
